server:
  port: 8080

spring:
  application:
    name: openchat-web

logging:
  level:
    root: INFO
    org:
      springframework: INFO
    org.springframework.data.mongodb: DEBUG
  file:
    name: /var/log/openchat/web.log
    max-size: 50MB
